// components/tokendetial.js
import { useState } from "react";
import Head from "next/head";
import styles from "../styles/Home.module.css";

import Header from "../components/header";
import TokenDetail from "../components/TokenDetail";
// import TokenPools from "../components/TokenPools";
// import TokenValueCalculator from "../components/TokenValueCalculator";
// import MutualToken from "../components/MutualToken";
import Ohlcv from "../components/OHLCV";

export default function Tokendetial() {
  return (

    <section className={styles.container}>

      <Head>
        <title>Web 3</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


      <main className={styles.main}>
        <Header />
        <TokenDetail>
          {/* <Ohlcv> */}

          {/* </Ohlcv> */}
        </TokenDetail>
        
      </main>
    </section>
  );
}
